apiVersion: v1
kind: Service
metadata:
  name: react-todo-app-service
  namespace: poc
spec:
  type: NodePort
  selector:
    app: react-todo-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30007
